language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-27.0.3    
    - android-27

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

os:
  - linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
before_script:
  - chmod +x gradlew
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
  - mkdir -p $HOME/.android # silence sdkmanager warning
  - echo 'count=0' > $HOME/.android/repositories.cfg # silence sdkmanager warning
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'tools' 'platform-tools' 'build-tools;27.0.3' > /dev/null
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platforms;android-27' > /dev/null

script:
  - ./gradlew build connectedCheck
