language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-27.0.3
    - android-27
    - android-15
    
    - tools
    - platform-tools
    - tools

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    
before_script:
  - chmod +x gradlew  
  
script:
  - ./gradlew clean build
  
notifications:
  webhooks: https://maker.ifttt.com/trigger/travis_ci_datamuseandroid/with/key/b2G71lyF5hnO5cO3avYaNA3kRdCe-nZsFOMhWUADAAo
